export const JWT_TOKEN_LOCAL_STORAGE_KEY = 'jwt';

export const HEADER_HEIGHT = 106;

export enum QUERY_KEYS {
  AUTHENTICATED_USER = 'AUTHENTICATED_USER',
  USERS = 'USERS',
}

export enum MUTATION_KEYS {
  CREATE_USER = 'CREATE_USER',
  DELETE_USER = 'DELETE_USER',
}
